// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjWc6r1Hm4F2K8wxzljUqIbCPV_4L68iE',
    appId: '1:80990778642:web:27d27768d01de19c3eafcb',
    messagingSenderId: '80990778642',
    projectId: 'linguacall-ai-4bfd5',
    authDomain: 'linguacall-ai-4bfd5.firebaseapp.com',
    storageBucket: 'linguacall-ai-4bfd5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkX1NT26Iz0AKz5baPG7zhAJ-s5TIwirQ',
    appId: '1:80990778642:android:86f23eae4cb3f3b33eafcb',
    messagingSenderId: '80990778642',
    projectId: 'linguacall-ai-4bfd5',
    storageBucket: 'linguacall-ai-4bfd5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG0NdfiEak7AB_9ABUcNGwaPqLZhWs_mE',
    appId: '1:80990778642:ios:03e68e179a29f41c3eafcb',
    messagingSenderId: '80990778642',
    projectId: 'linguacall-ai-4bfd5',
    storageBucket: 'linguacall-ai-4bfd5.firebasestorage.app',
    iosBundleId: 'com.linguacall.linguacall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG0NdfiEak7AB_9ABUcNGwaPqLZhWs_mE',
    appId: '1:80990778642:ios:03e68e179a29f41c3eafcb',
    messagingSenderId: '80990778642',
    projectId: 'linguacall-ai-4bfd5',
    storageBucket: 'linguacall-ai-4bfd5.firebasestorage.app',
    iosBundleId: 'com.linguacall.linguacall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjWc6r1Hm4F2K8wxzljUqIbCPV_4L68iE',
    appId: '1:80990778642:web:b755406b2612c6303eafcb',
    messagingSenderId: '80990778642',
    projectId: 'linguacall-ai-4bfd5',
    authDomain: 'linguacall-ai-4bfd5.firebaseapp.com',
    storageBucket: 'linguacall-ai-4bfd5.firebasestorage.app',
  );

}